// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/26/2024, 6:37:12 AM
const configMerger = require("/Users/kriswale/Web Dev/portfolio-website/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/kriswale/Web Dev/portfolio-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kriswale/Web Dev/portfolio-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kriswale/Web Dev/portfolio-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kriswale/Web Dev/portfolio-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kriswale/Web Dev/portfolio-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kriswale/Web Dev/portfolio-website/plugins/**/*.{js,ts,mjs}","/Users/kriswale/Web Dev/portfolio-website/composables/**/*.{js,ts,mjs}","/Users/kriswale/Web Dev/portfolio-website/utils/**/*.{js,ts,mjs}","/Users/kriswale/Web Dev/portfolio-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kriswale/Web Dev/portfolio-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kriswale/Web Dev/portfolio-website/app.config.{js,ts,mjs}"] }));

module.exports = config
